# The future of metal mining# 

```{block, type='chap-auth'}
Jan Johansson, Lena Abrahamsson and Bo Johansson
```

In this chapter, we will discuss the challenges facing today\'s metal mining industry. Our statements about the future should be seen as a contextual background to the discussions presented in the following chapters

The world\'s metal mining industry is rapidly changing and faces several challenges that must be addressed with a sociotechnical approach that covers the whole mining and minerals value adding chain, including environmental issues. We have tried to capture this uncertain future in fifteen predictions presented below:

1.  Future mining will be shaped in a context where it is necessary to produce at costs that are determined in *international competition*. The prices of metals and minerals are set by the market, but in the long term, there is little doubt that the demand is increasing. Large nations such as China, India, Indonesia, Brazil and the whole of Africa will require a larger share of consumption, which is leading to the opening of new mines. The difference between these countries\' annual "per capita" consumption and Western Europe can be greater than 10 times.

2.  Production conditions will be characterized by the fact that nearby and easily accessible ores will be mined first. *New ores will also become more distant or found in the depths*. Large ore reserves are located under the sea, and there is little doubt that the mining and offshore companies will develop new technology to extract these reserves. In both cases, production costs will increase.

3.  Mining depths increase, and that increase brings new stability problems. The role of rock mechanics in the design of layouts, cutting sequences, strata stabilization, and roof bolting, etc., must be a central issue for the future. *Full face drilling and cutting* should be interesting from a safety perspective, both directly in safer drifting operations and because it can create more-stable galleries due to reduced or no blasting damages. Cutting should also be useful for selective mining of high-quality ore in narrow ore bodies. Production drilling and blasting for *controlled fragmentation* are two very crucial operations in the ore mining cycle. Improvements in these operations open up many possibilities for *automation*.

4.  *Environmental requirements* affect both energy consumption and management of ore tailings. The discussion of energy consumption is largely linked to global warming and carbon emissions. Today, not all nations have joined the Paris Climate Agreement, but in the long term, some form of coordination surely will be established. The cost of emission allowances will be a significant factor to consider.

5.  The mining industry is an *energy-intensive industry*, with high CO~2~ emission. Improvement of energy efficiency will increase economic profitability and reduce environmental impact. There are many components that affect total energy consumption; one often discussed is underground pre-concentration (*in situ*). This approach directly affects the energy-consuming hoisting and milling. The use of fossil diesel fuel is extensive and causes environmental burdens. A transition to electric power and battery operation is in progress.

6.  The discussion of *waste management* is about leaving as few footprints in nature as possible. We must not leave toxic substances that leak out into nature, and the landscape should be restored as much as possible. One solution discussed is *in situ mining*, where as much as possible of the production and processing will take place underground. Such technology is however not without environmental risks and risks for health and safety. Pollution of mine water is the single most important environmental issue for the mining sector and consequently also affects mine water treatment. Regarding water in general, it is a question of *closing the loop*s and re-using the process water as much as possible.

7.  The environmental debate also includes a discussion on the mining industry\'s *social responsibility* for the welfare of the local community. In addition to preserving the environment, they are supposed to build a strong technical and social infrastructure that ensures the survival of society after mining has ceased.

8.  Health and safety at work must have top priority. Mechanization, remote control and automation are efficient preventive safety measures. They are also appropriate for reducing workload to avoid musculoskeletal injuries and allow for recovery periods. New technology makes it possible to both warn of dangerous working conditions and monitor employees\' health conditions in real time. Improved safety is also a matter of a developed safety climate in the form of relevant education, rules and effective leadership, with safety prioritized in the day-to-day workplace.

9.  Many problems in the work environment in present mines (and in other industries) can be traced back to insufficient initial physical planning and design. Since mining is characterized by huge investments and long-term operations, it is very important to have a well-designed physical production system. The physical layout also influences and limits the organizational aspects. If initial mistakes are made, personnel will have to bear the negative consequences for many years to come. The initial design phases of every major development project are therefore critical for establishing a safe and attractive physical and psychosocial work environment in a mine.

10. *Industry 4.0* is based on implementations of the Internet of Things, 5G and big data, where the entire production process is included in internet-based networks that transform the mines into smart mines. We will soon see the outlines for Mining 4.0, where miners equipped with minicameras can, for everyday and emergency situations, provide their colleagues and senior management with information that is difficult to convey verbally.

11. *The extended business* and *open collaboration* are two concepts where Virtual Reality (VR) technology can be used to link production functions such as planning, mining, maintenance, logistics, purchasing and for the coordination of external contractors, suppliers, and customers, etc., all connected to a production flow, a value adding chain, where all share the same goal and everyone sees the same whole. Common visualization of problems and opportunities in the system allows for all to optimize the whole chain rather than suboptimizing parts.

12. N*ew professional roles* with a higher proportion of remote control from production centres and *collaborative visualization rooms*, perhaps located in nearby communities or further away (other continents), where the operators have monitoring and coordinating activities across the value chain. Their jobs will change character towards service work, and the new tasks require different kinds of skills. In addition to dealing with advanced information technology, the miners have to interact with different specialist teams located all over the world.

13. New technology creates a new type of work -- new in terms of *competencies and knowledge* and workload. There is an emerging, and in many aspects already evident, knowledge transformation from the old and obsolete physical and tacit knowledge and skills (for example, the ability to 'read the rock') to something new that can be described as abstract knowledge. This transformation can challenge the identity of the miners and create resistance to change.

14. Future efficient mining operations will be dependent upon a highly competent and well-motivated work force, on all levels. The mining companies will have to recruit their personnel from a limited group of talented individuals with high demands and expectations with respect to future work. To cope with the future labour supply, the mining industry must change the image of mining work and increase the attractiveness of working in the sector, especially for young women and men.

15. The mines of the future will have smaller staffing, and it is also clear that they will meet a different kind of *model for work organization* than they do today. Mining companies will gradually turn to a flat and *lean organization* with multiskilled workers who can operate in several areas and functions within the company. There is also a discussion about a staffing system based on the *fly-in/fly-out* method, which is more independent of a local community.

There are of course other important areas of development, but those discussed above are expressed as the most important from a long-term strategic and sustainable view. A major conclusion is that the challenges and the changes are so large and numerous that comprehensive international cooperation is needed both within and outside the industry to succeed. Working separately would lead to a far too slow development, something that is undesirable for both the companies and the miners. Another conclusion is that a successful mining industry must work simultaneously with all the problems mentioned above. There is a need for a new and modern vision for the whole industry based on a sociotechnical approach that covers the whole mining and minerals value adding chain including environmental issues.
