# A vision of "The New Attractive Mine"# 

```{block, type='chap-auth'}
Jan Johansson and Bo Johansson
```

In this chapter, we have tried to create a vision of a future mine, considering the working environment and attractiveness all the way from the mine planning stage.

The new deep metal mine was a true planning and cooperation success and a huge leap in mining history. Several leading "European mining companies" had been inspired by the EU \"Sustainable Intelligent Mining Systems\" project, which is abbreviated as SIMS. This successful project had provided a conceptual system for automated and flexible mining, based on drill and blast technology for fragmentation of the actual ore. Continuous mining with road headers was still only used in development works where conventional drilling and blasting was abandoned. The zero entry mine was now almost realized, and the large "European manufacturers of advanced mining equipment" had contributed largely to the technological success, which had opened a new global market for them.

The new automated mining method made it possible to almost continuously produce desired ore qualities and quantities on customer demand. This ability was a large comparative advantage compared with the old traditional bulk production mines that still existed and struggled for survival. The new mining system dramatically reduced the prevailing and traditional use of expensive storing and stacking of mined ore. With the new approach to mining, an important first step towards true lean-mining was taken; gradually, one bottleneck after another was discovered and eliminated. Metal recovery was very high, and cut-off grades were reduced. It seemed as though traditional mining had been a real waste of resources.

Advanced investment analyses had clearly shown that there were great financial benefits with the new automated mining technology. The costs for underground development works were reduced by approximately 50% compared with traditional mining methods, and labour costs were reduced by more than that. These cost reductions made it possible for the companies to make large investments in new technology and personnel competence and still be highly profitable. If profits for society and individuals were also included in the analysis, the total expected financial benefits where overwhelming. Follow-up of actual economical results showed even greater savings than expected.

An unusual feature of the new mine was that open pit mining was avoided, although the upper parts of the ore body were close to the surface. A green mining philosophy, "*In situ* mining", was applied, and most of the mining activities were invisible for people passing the mine site. Most of the waste material was directly used for backfilling after recovering the metal content.

The mining companies had from the start of the project made use of a newly developed iterative planning methodology that reduced common initial design errors when they designed the new mine. Basic guidelines provided very useful demands for the mine designers. During the development work, there had for example never been any real ventilation problems, stability problems or water drainage problems. No severe accidents or incidents had occurred so far, and all mining activities were systematically risk assessed. The new mine had set a new world standard for results regarding health and safety results. Safety first was not only a simple slogan; it was a complex and applied reality. In fact, no major physical work or main activities were performed unless they had been computer simulated, evaluated and approved. This proactive means of addressing production and safety risks had proven its value time after time. The old description of mining work as "dark, dirty and dangerous" had definitively become out of date and irrelevant. Instead of being almost unpredictable and uncertain, mining had become highly predictable. Some of the old miners felt that the original charm of mining was somewhat lost when all worked according to plans, but no one truly wanted the old risky ways and days back.

One key to the success was the fact that the mine was already from the start designed for automation and sociotechnical principles, with a work organization based on production teams and broad professional skills among management and miners. One of the mine's most impressive features was the information and decision systems based on sensor technology and production analysis in real time. This system made it possible for the personnel to actively steer and control production instead of just passively reacting to deviations and alarms from an automated production process. This ability constituted a major difference and advantage compared with traditional control room work in, for example, regular processing plants. Impressive results regarding product quality and production availability and stability had been achieved due to this proactive philosophy. The philosophy also made the miners' work interesting and challenging.

The new remote-operations control centres (ROCs) were designed to promote cooperation and creative problem-solving in multiskilled teams. The working teams were mixed regarding age, experience, gender, and competence, etc. Diversity had replaced conformity and proved a good base for creating "production scouts", miners who were always ready and interested in improving the mining processes. Most of the team members were recruited from national and regional education programmes that were specifically developed with regards to the new demands that the mining sector had, basically that modern mining was intellectual analytical work for wise and reliable persons. New education programmes on all levels had been started and were recruiting well. Mining work had become attractive, not only because of the wages but also because it was very interesting work with good possibilities for personal and professional development in a safe and sound working environment.

Total progress had been astonishing, although they had only started to utilize parts of the potential that the new technology and organization offered. Investments in research and development work had paid off quickly, and management were convinced that innovative R&D combined with a challenging vision had been and would continue to be the key factor for success.
