# A vision of "The New Attractive Mine"

The new deep metal mine was a true planning and co-operation success and
a huge leap in mining history. A number of leading "European mining
companies" had been inspired by a group of "Australian researchers" that
had provided a conceptual system for automated and flexible mining,
based on drill and blast technology for fragmentation of the actual ore.
Continuous mining with road headers was still only used in development
works where conventional drilling and blasting was abandoned. The zero
entry mine was now almost realised and the large "European manufacturers
of advanced mining equipment" had contributed largely to the
technological success, which had opened a new global market for them.

The new automated mining method made it possible to almost continuously
produce desired ore qualities and quantities on customers demand. This
was a big comparative advantage compared to the old traditional bulk
production mines that still existed and struggled for their survival.
The new mining system dramatically reduced the prevailing and
traditional use of expensive storing and stacking of mined ore. With the
new way to mine an important first step towards true Lean-mining was
taken and gradually one bottle neck after another was discovered and
eliminated. Metal recovery was very high and cut-off grades were
reduced. It seemed as traditional mining had been a real waste of
resources.

Advanced investment analyses had clearly shown that there were great
financial benefits with the new automated mining technology. The costs
for underground development works were reduced with about 50% compared
with traditional mining methods and labour costs were reduced with more
than that. This made it possible for the companies to make large
investments in new technology and personnel competence and still be
highly profitable. If profits for society and individuals also were
included in the analysis the total expected financial benefits where
overwhelming. Follow up of actual economical results showed even bigger
savings than expected.

An unusual feature of the new mine was that open pit mining was avoided
although the upper parts of the ore body were close to the surface. A
green mining philosophy "In situ mining" was applied and most of the
mining activities were invisible for people passing the mine site. Most
of the waste material was directly used for backfill after recovering
the metal content.

The mining companies had from the start of the project made use of a
newly developed iterative planning methodology that reduced common
initial design errors when they designed the new mine. Basic guidelines
provided very useful demands for the mine designers. During the
development works there had for example never been any real ventilation
problems, stability problems or water drainage problems. No severe
accidents or incidents had occurred so far and all mining activities
were systematically risk assessed. The new mine had set a new world
standard for results regarding health and safety results. Safety first
was not only a simple a slogan, it was a complex and applied reality. In
fact no major physical work or main activities were performed unless
they had been computer simulated, evaluated and approved. This proactive
way to handle production and safety risks had proven its value time
after time. The old description of mining work as "Dark, dirty and
dangerous" had definitively become out of date and irrelevant. Instead
of being almost unpredictable and uncertain mining had become highly
predictable. Some of the old miners meant that the original charm of
mining was somewhat lost when all worked according to plans, but no one
really wanted the old risky ways and days back.

One key to the success was the fact that the mine was already from the
start designed for automation and socio technical principles with a work
organization based on production teams and broad professional skills
among management and miners. One of the mines most impressive features
was the information and decision systems based on sensor technology and
production analysis in real time. This made it possible for the
personnel to actively steer and control the production instead of just
passively react on deviations and alarms from an automated production
process. This was a major difference and advantage compared with
traditional control room work, in for example regular processing plants.
Impressive results regarding product quality and production availability
and stability had been achieved due to this proactive philosophy. The
philosophy also made the miners work interesting and challenging.

The new remote operations control centres (so called ROCs) were designed
to promote co-operation and creative problem solving in multi skilled
teams. The working teams were mixed regarding age, experience, gender,
competence, etc. Diversity had replaced conformity and this had proved
to be a good base for creating "production scouts", miners that were
always ready and interested in improving the mining processes. Most of
the team members were recruited from national and regional education
programs that were specially developed with regards to the new demands
that the mining sector had, basically that modern mining was an
intellectual analytical work for wise and reliable persons. New
education programs on all levels had been started and were recruiting
well. Mining work had turned to be attractive, not only because the
wages, but also because it was a very interesting work with good
possibilities for personal and professional development in a safe and
sound working environment.

The total progress had been astonishing although they only have started
to utilize parts of the potential that the new technology and
organisation offered. Investments in research and development work had
paid off quickly and management were convinced that innovative R & D
combined with a challenging vision had been and would continue to be the
key factor for success.

## See also {-}

\ @Johansson2014.
