# Future of metal mining

The world's metal mining industry is rapidly changing and faces a
number of challenges which must be addressed with a socio-technical
approach that covers the whole mining and minerals value adding chain
including environmental issues. We have tried to capture this uncertain
future in fourteen predictions presented below:

1.  Future mining will be shaped in a context where it is necessary to
    produce at costs that are determined in *international competition*.
    The prices of metals and minerals are set by the market but in the
    long term, there is little doubt that the demand is increasing.
    Large nations like China, India, Indonesia, Brazil and the whole of
    Africa will require a larger share of consumption which is leading
    to the opening of new mines. The difference between these
    countries\' annual "per capita"-consumption and Western Europe can
    be more than 10 times.

2.  Production conditions will be characterized by the fact that the
    nearby and easily accessible ores will be mined first. *New ores
    will also become more distant or found in the depths*. Large ore
    reserves are located under the sea and there is hardly any doubt
    that the mining and off-shore companies will develop new technology
    to extract these. In both cases, production costs will increase.

3.  Mining depths increase, and it brings new stability problems. The
    role of rock mechanics in the design of layouts, cutting sequences,
    strata stabilization, roof bolting etc. must be a central issue for
    the future. *Full face drilling and cutting* should be interesting
    from a safety perspective, both directly in safer drifting
    operations and also in that it can create more stable galleries due
    to reduced or no blasting damages. Cutting should also be useful for
    selective mining of high quality ore in narrow ore bodies.
    Production drilling and blasting for *controlled fragmentation* are
    two very crucial operations in the ore mining cycle. Improvements in
    these operations opens up many possibilities for *automation*.

4.  *The environmental requirements* affect both energy consumption and
    management of ore tailings. The discussion of energy consumption is
    largely linked to global warming and carbon emissions. Today not all
    nations have joined the Paris Climate Agreement, but in the long
    term, some form of coordination surely will be established. The cost
    of emission allowances will be a significant factor to consider.

5.  The mining industry is an *energy-intensive industry* with high
    CO~2~ emission. Improvement of energy efficiency will increase the
    economic profitability as well as reducing environmental impact.
    There are many components that affect the total energy consumption;
    one often discussed is underground pre-concentration (in situ). It
    affects directly the energy consuming hoisting and milling. The use
    of fossil diesel fuel is extensive and causes environmental
    burdens. A transition to electric power and battery operation is in
    progress.

6.  The discussion of *waste management* is about to leave as few
    footprints in nature as possible. We must not leave toxic substances
    which leak out into nature and the landscape should be restored as
    far as possible. One solution discussed is *in situ mining* where as
    much as possible of the production and processing will take place
    underground. Such technology is however not without environmental
    risks and risks for health and safety. Pollution of mine water is
    the single most important environmental issue for the mining sector
    and consequently also effective mine water treatment. With regard to
    water in general it is a question about *closing the loops* and
    re-using the process water as much as possible.

7.  The environmental debate also includes a discussion on the mining
    industry\'s *social responsibility* for the welfare of the local
    community. In addition to preserving the environment they are
    supposed to build a strong technical and social infrastructure that
    ensures survival of society after mining has ceased.

8.  *Health and safety* are very high on the agenda and are also strong
    driving forces behind the ideas of automation. In the future we will
    have a production with *zero entry* for employees underground based
    on automation and remote control

9.  A generally good and safe working environment is seen as a
    prerequisite for the recruitment of skilled workers. The typical
    underground *work environment* with noise, dust and toxic fumes and
    gasses will be monitored by using advanced sampling strategies with
    portable, more accurate and reliable measuring devices and more
    efficient counter measures can be taken.

10. *Industrie 4.0* is based on implementation of Internet of Things, 5G
    and Big data where the entire production process is included in
    internet-based networks that transform the mines to smart mines. We
    will soon see the outlines for Mining 4.0 where miners equipped with
    mini cameras can for everyday and emergency situations provide their
    colleagues and senior management with information that is difficult
    to convey verbally.

11. *The extended business* and *open collaboration* are two concepts
    where VR technology can be used to link production functions such as
    planning, mining, maintenance, logistics, purchasing and for
    coordination of external contractors, suppliers, customers, etc. all
    connected to a production flow, a value adding chain, where all
    share the same goal and everyone sees the same whole. Common
    visualization of problems and opportunities in the system allows for
    all to optimize the whole chain rather than sub-optimizing parts.

12. *New professional roles* with a higher proportion of remote control
    from production centers and *collaborative visualization rooms*,
    perhaps located in nearby communities, or further away (other
    continents), where the operators have monitoring and coordinating
    activities across the value chain. Their jobs will change character
    towards service work and the new tasks require different kinds of
    skills. In addition to deal with advanced information technology the
    miners have to interact with different specialist team located all
    over the world.

13. New technology create a new type of work - new in terms of
    *competencies and knowledge* as well as workload. There is an
    emerging, and in many aspects already evident, knowledge
    transformation -- from the old and obsolete physical and tacit
    knowledge and skills (for example the ability to 'read the rock') to
    something new which can be described as abstract knowledge. This can
    challenge the identity of the miners and create a resistance to
    change.

14. The mines of the future will have a smaller staffing and it is also
    clear that they will meet a different kind of *model for work
    organization* than today. Mining companies will gradually turn to a
    flat and *lean organization* with multi-skilled workers who can
    operate in several areas and functions within the company. There is
    also a discussion about staffing system based on *fly-in fly-out*
    which is more independent of a local community.

There are of course other important areas of development, but the above
discussed are expressed as the most important from a long-term strategic
and sustainable view. A major conclusion is that the challenges and the
changes are so large and numerous that a comprehensive international
cooperation is needed both within and outside the industry in order to
succeed. Working separately would lead to a far to slow development,
something that is undesirable for both the companies and the miners.
Another conclusion is that a successful mining industry must work
simultaneously with all the problems mentioned above. There is a need
for a new and modern vision for the whole industry based on a
socio-technical approach that covers the whole mining and minerals value
adding chain including environmental issues.

## See also {-}

\ @Abrahamsson2009.
