# Meeting social challenges in established mining communities # 

```{block, type='chap-auth'}
Eugenia Segerstedt
```

In this chapter, we will broaden the frame of reference and discuss the mining industry\'s responsibility to operate in a socially sustainable society. By "established mining communities", we mean communities that co-exist with ongoing mines and mining companies. In Sweden, these communities are often rural and small or midsized towns.

Such towns face many practical challenges that provide both possibilities and obstacles to supporting socially sustainable development, challenges that they in varying degrees share with mining communities in countries such as Norway, Finland, Australia, and Canada. Many of these communities have always been, and indeed still are, at the mercy of global market fluctuations in the mining, steel, and forestry sectors. They are situated in districts that are home to highly valued natural areas, major tourist attractions, and mixed populations where indigenous peoples are an important presence; in some cases, these areas are sources for important and difficult discussions and debates, and occasionally even overt conflicts. Examples of deep-rooted and persistent problems in these communities include the following: low education levels (especially among men), depopulation (as women and young people move away), economic stagnation, downsized welfare services, a low level of activity in other sectors (trade, housing, communication, and infrastructure), and a gender-segregated labour market with a low degree of differentiation. Those two last aspects distinguish industrial communities from small rural communities. In addition, these areas are often characterized by a social construction of rural citizens (especially men) as "old fashioned" and culturally conservative.

The problems outlined above are undoubtedly substantial, but some of them are offset by periods of more positive trends such as a low level of unemployment, new investments in housing and infrastructure, and growing entrepreneurial activity. Many of those challenges are relevant for rural industrial communities, but some are specific to mining communities. In periods when mining is booming, the problems change character and become related to, for example, lack of housing and infrastructure and the difficulty in recruiting new employees with the right skills, both for the mining companies and other ancillary businesses and welfare services such as healthcare. Other major challenges relate to the environment, more specifically, to how to balance the mining companies' need for efficient licensing with environmental concerns. Moreover, even if we can see an emerging diversity of livelihoods, the recent mining boom mainly led to an increase in activity in businesses and industries that have long been dominated by men.

Aspects of urban life in established mining communities such as social cohesion and inclusion, migration and demographics, good housing infrastructure, and gender equality can enable (or disable, in a figurative sense) diversity of livelihoods in those communities. A strong community identity can be seen as good grounds for social cohesion, but at the same time, this result can be associated with a certain lifestyle that is not inclusive, for example, if this lifestyle has a connection with traditional (specifically rural and mining worker) masculinity. Concerning social cohesion and inclusion, some studies focus on the local community with respect to decision-making processes (e.g., issuing a "social license to mine"). Swedish studies of mining communities discuss strong community identity, which can be seen as promoting cohesion, but as alluded to above, this identity is often associated with a certain lifestyle that is not inclusive and is characterized by "traditional masculinities". Some international studies have also found mining communities to be notably cohesive internally, but local networks were not considered strong *and* inclusive.

Crawley and Sinclair (2003) have examined how to broaden a mining company's recruitment base by including indigenous people, a strategy based on power sharing. The conclusions in the study placed high hopes on the UN declaration on the Rights of Indigenous People that was being discussed at the time of the study and that was adopted later in 2007. One might argue though that the UN declaration lacked the ability to alter the normative environment for mining companies. Indeed, the aftermath of the declaration proved to be something of a disappointment because it became clear that it did not---perhaps could not---change things anywhere near enough for indigenous people; rather, positive advances would, as so often in the past, come from local pressures exerted and directed from below. There is an undeniable ambition to preserve indigenous peoples' cultural expressions. Australian and North American studies have examined how the mining industry has negatively affected indigenous people by severely limiting their ability to practice their traditional lifestyle. The concern is often with indigenous peoples' rights and access to prior, free, and informed consent to mine, for example, as these issues relate to international law.

The practical implications of these challenges are the following:

-   Measures towards community cohesion might be problematic.

-   Social licensing should be a continuous process, a dialogue between the mining company and the established mining community.

-   Working towards a less gender-segregated local labour market is essential.

-   It is important to work for indigenous peoples' rights and access to prior, free, and informed consent to mine.
