# Gender and gender equality# 

```{block, type='chap-auth'}
Lisa Ringblom
```

The mining industry is exceedingly male-dominated. Globally, the workforce consists of approximately 90 per cent men but with great variation depending on country, mineral and company. In the world's top 500 listed mining companies only seven of these have a woman as CEO and about eight per cent of board representatives of these companies are women. Although mining has a significant history as work for and by men, this has not always been the case. A historical perspective on mining shows that the mine and its workplaces have not always been an arena solely for men. Depending on time and geographic location in history women have participated in all areas of the mining process. For example, in Sweden before the industrialization the number of women were at some mines as high as 55 per cent of the workforce. Due to the changes that came with the industrialization a statutory ban on women in underground work was implemented in 1900, a law that was repealed first 1978. The ban on women underground followed a more general ideological shift of societal norms that took place during industrialization, which affected the relationship between men and women. With the development of a stronger division between paid and unpaid work, a women's place was first and foremost seen as the one as a wife and mother and women\'s salaried employment was predominantly seen as a complement to that of men. The exclusion of women in mining is not unique to Sweden, but is also found in other national contexts such as the United Kingdom, China and Peru. The reason for women\'s more or less temporary exclusion from mining work at different times in history has been legitimated with all from superstition (e.g. beliefs concerning misfortune with women underground) to national structural changes.

The mining industry is not only male-dominated but also characterized by masculinity. Traits that traditionally have been labelled masculine, such as being strong, brave, and tough, etc., are still ideals within mining. A "macho-masculinity" has to a large extent ruled structures, practices and procedures for the blue-collar working professional and professional ideals of mining. This type of macho-masculinity, associated with characteristics that are largely related to a physical body, such as practical knowledge, physical strength and endurance under stressful and risky working conditions, have connections to increased risk-taking, which in mining can have devastating outcomes for organizations but primarily for the individual in terms of injuries and ultimately death. Research on the link between gender and safety work in the mine has shown how the idealized macho-masculinity premise of risk-taking poses a potential safety risk at work. These conservative ideas concerning gender can also be problematic during organizational and technological change and can create implementation problems and restoration responses. Because of the male dominance and the idealized macho-masculinity, mining organizations risk conflating gender with competence, something that can function as an effective exclusion mechanism in these workplaces for those who are not perceived as fitting the norm of a "real" mineworker, i.e., women. The historical exclusion of women from mining work, the dominant ideal of macho-masculinity, and men\'s numerical dominance has created an opportunity for constructing women as deficient and deviant in relation to mining. This construction has contributed to the fact that women have not been able to participate in mining work under the same conditions as men and is expressed through, for example, stereotyping and sexualization of women. Sexism, sexual harassment and discrimination are recurring themes in women\'s working life in the mine.

Although men and macho-masculinity dominate mining, when gender and gender equality is actualized in the mining industry, it tends to focus on women. For example, when a mining organization raises gender as an issue, it is commonly the (often) low proportion of women that tends to be in focus. This issue is of course an important question to increase women's participation in mining and to have the benefits of mining be more equally distributed between men and women. However, focussing only on the number of women is not the entire solution for the male bias in the mining industry. Women should not only have the opportunity to enter but also want to stay in the industry. To increase gender awareness and to improve gender equality demands more from organizations than counting heads. In other words, more-qualitative measures that focus on the terms for men and women in the industry also need to be implemented, that is, actions that challenge the unequal structures that do not necessarily change with an equal distribution of women and men. To have a gender perspective and to work for increased gender equality does not mean a sole focus on women; men are not to be left out of the equation.

What is understood as "appropriate" work for men or women is not a law of nature; it is possible to change, as are organizational cultures and the degree of diversity in the workforce. A long-term responsibility and commitment towards a socially sustainable development in mining needs to take gender issues into account in a broad range of ways, concerning both organizational issues and the gendered implications for the surrounding communities. Issues for women in the work environment in male-dominated organizations are usually an indication that the work environment is not healthy for anyone. Even if women are especially exposed in a male-dominated workplace, there are good reasons to believe that the work environment is problematic for all.

-   Gender equality means that women and men have the same rights, responsibilities and opportunities in all areas of life. So, gender is not a women's issue. Gender equality concerns *both* women and men.

-   In a male-dominated industry as mining, to attract and recruit (more) women is an important step towards improved gender equality. *But*, to just focus on the number of women entering the industry is not enough. For example, women could be entering *and* leaving the industry within a short period of time which means that both in-flux and out-flux are important aspects. Most importantly however, is to analyze and examine the organizational terms and conditions for women *and* men within the organization. To increase gender equality in a sustainable and long- term way demands knowledge, time, resources and systematic work.

-   At last, changing the question could lead to other solutions. Instead of asking why there are few women working within the mining industry, a maybe more interesting question would be -- Why is there so many men?

**References:**

Abrahamsson, L. (2007). Gruvarbetets historia ur ett genusperspektiv. Hur gruvarbetet blev och förblev manligt \[The history of mining from a gender perspective. How mining became and remained male\]. In: Doktare, H. (Ed.). *OPLOGAT -- spår av kvinnors liv och arbete i Norrbotten* \[UNPLOWED- traces of women\'s lives and work in Norrbotten\]. Luleå: Oplogat produktion.

Abrahamsson, L., Segerstedt, E., Nygren, M., Johansson, J., Johansson, B., Edman, I., & Åkerlund, A. (2014). *Mining and Sustainable Development: Gender, Diversity and Work Conditions in Mining*. Luleå: Luleå University of Technology.

Andersson, E. (2012) *Malmens manliga mysterium -- en interaktiv studie om kön och tradition i modernt gruvarbete*. \[The male mystery of iron ore -- an interactive study on gender and tradition in contemporary mining\]. Doctoral thesis. Luleå: Luleå University of Technology.

Ringblom, L. (2019). *Utmanad ordning? En studie av kön och jämställdhetsarbete i den svenska gruvindustrins arbetsorganisationer*. \[Challenging the gendered order? A study of gender and gender equality work in the Swedish mining industry\]. Doctoral thesis. Luleå: Luleå University of Technology.

