# Can technology improve gender equality in mining? # 

```{block, type='chap-auth'}
Lisa Ringblom
```

Few professions have such an aura of masculine symbolism as mining work. Work in the mine has historically been characterized by heavy body work in a risky work environment. Notions concerning who is considered a "real" miner and what the work in the mine implies, to a large extent, still constitute the story of a man that with his physical strength and practical skills masters the profession. This point is notable since many of the workplaces in the mine today are considerably mechanized and digitalized and that women are part of the workforce. The work is in many ways characterized by both new and advanced technology, and there is an accelerated pace of change in this area, bringing new work-tasks, competence demands and new ways of organizing mining work. As a result, mine work is changing due to technology development, potentially having an impact concerning gender equality.

The technical development that has been evident in the mining sector in recent decades is often described as part of the explanation that has enabled women's increased participation in the workforce and the main reason that women now work in the mine to a greater extent than before. However, technology as an explanation for women's increased participation in mining is somewhat puzzling. Historically, technology (its development and use) has to a large extent been linked to men and masculinity. Hence, male miners and the dominating ideal of macho-masculinity has a somewhat different relation with new technology in the workplace. Here, traditional tools and working methods with an emphasis on manual labour is an important part of the professional identity as a miner. Historically, there has been a gender barrier on work in the mine as being for and by men. Today, the boundary has been moved down in the mine and is rather between the mining work which has more manual elements and which is considered to be work primarily for men, and the work carried out using remote control, machines and automation and which is understood as being for both men and women. This change could partly explain the occurrence of mining men\'s distancing and resistance to new technology, and somewhat of a feminization of new technologies such as automation, digitization and robotization.

There is a recurring story within the mining industry that women are particularly suited as machine operators. It is often said that women drive the machines more carefully, which leads to improved safety and lower maintenance costs. In an Australian context, there are examples of how new giant mining trucks and bulldozers weighing over 20 tons became \"women\'s machines\" and, as a result, the male miners refused to drive them. This behaviour is an interesting aspect, since heavy machinery in the world outside mining is not usually seen as suitable for women but rather an area of men. New technology could be understood as challenging the traditional ideals of mining professionals. In a Swedish context, there are for example studies showing that when the first front loaders were moved from their machines underground to control the machines from the control centre above ground, they still looked similar to miners and went to the dressing room as usual to change clothes before each shift, although they were now working in a clean office environment. Miners underground, especially those who worked with more manual tasks, gave the remote controllers nicknames such as \"velour workers\", called the control centre the \"seventh heaven\" or in other ways clearly indicated that the remote controllers up at the control centre were not \"real\" miners (although they were men). Over time, this ritual ceased, but it indicates uncertainty in a new professional role and makes clear that the step away from traditional underground mining was difficult to take.

The increased proportion of women in mining work, is many times understood in relation to new machines and technical solutions that have created a better and safer working environment, which meant that certain tasks has become physically easier and thus also possible for women to perform. This explanation might be more ideological than real enabler since neither advanced technology nor a good working environment are necessarily indications for occupations or workplaces with a high proportion of women. Furthermore, if there is a link between automation and similar new technology and an increased proportion of women in these male-dominated workplaces, there is a certain lag. Admittedly, technology development in the mine may be said to have accelerated in recent years, but automated machinery and other technical equipment has existed for a considerable amount of time.

The technical development in mining has been connected to the increased participation of women in mining during the last decade, since technological changes has improved the work environment and enabled women to participate due to the shift from manual to mechanized work. Even though the changes of mining work might have opened up for renegotiations concerning who can be a mine worker, technology is usually not the explanation for improved gender equality in work organizations in general. Technology, its development, implementation and use are an area that is commonly highly associated with men and masculinity and the tech-industry is an area of work that is highly male-dominated. This indicates that new male-dominated industry of digital technologies not necessarily will be the game changer concerning gender equality that the old male-dominated mining industry hopes for. The role of technology in mining and its relation to gender and gender equality could be both a window for change but could also in the long run reinforce mining as a male-dominated sphere. Therefore, the rapid technological development in the mine need to be closely monitored concerning its effect on gender equality and gender patterns within mining.

-   When developing and implementing new technology -- strive for inclusiveness of different perspectives and people along the entire chain. Who is regarded competent and why?
