# Industry 4.0 in a mining context# 

```{block, type='chap-auth'}
Erik Sundström, Lena Abrahamsson, Joel Lööw and Jan Johansson
```

## Industry 4.0

*Industry 4.0* is a strategy that was shaped by the German government in 2013. Industry 4.0 is described as the next great industrial revolution. After the steam engine, electricity and electronics, the revolution consists of an implementation of "Internet of Things, Humans and Services", where the entire production process is included in internet-based networks that transform ordinary factories into *smart* factories (Kagerman et al 2013). Similar concepts have appeared all over the world. The Chinese government promotes a similar idea under the name *Made in China 2025*, the Japanese government has launched *Society 5.0*, and the Swedish government uses the term *Smart Industry*.

Additionally, the German vision paints a bright picture of the future industry in which virtual and physical worlds will be linked into a powerful 'whole' through the integration of software; from product development and production, machines will not only do 'physical work' but also perform calculations. This approach is described as cyber-physical systems, or even socio-cyber-physical systems; smart ventilation, smart logistics, smart maintenance, smart machines and other smart systems continuously exchange information with each other and with human workers. The German strategy highlights the potential for skill development and a richer working life with more challenging work tasks.

## Mining 4.0

Industry 4.0 will also come to affect the mining industry. In fact, some mines have taken important steps towards the digitalized mine of the future. Gradually, the mining industry approaches more closely the visions of Industry 4.0, fully automated mines and more-technologically sophisticated ore processing facilities. Analogous to the application of Industry 4.0 in a mining context, we conceptualize Mining 4.0 as a mining operation where the miner is an expert who ensures that production runs smoothly. A Mining 4.0 operator is not confined to a control room. Instead, real-time process data and the status of machines follow the miners as they move around the mine. The miner solves problems on the spot by remotely interacting with other operators, experts, suppliers and customers in multicompetent teams. Production control could even be done in a digital model (or "digital twin") far away from the factory. In short, Mining 4.0 envisions an augmented miner with senses and memory extended through technology. This technology takes advantage of and supports human skills and increases situational awareness through sensors embedded in the clothes of the operator, for example, while maintaining an uninterrupted operational vigilance.

Romero et al. (2016) formed a typology of the future Industry 4.0 operator -- Operator 4.0. They built on eight characteristics that can be seen as the core of the new technology; we have modified them to relate to the future miner:

-   **Strengthened operator** -- Powered industrial exoskeletons assist with heavy loads and lifts, while also mitigating vibrations, which helps operators avoid musculoskeletal disorders from unergonomic work. In future mines, while much of the work will be done remotely, exoskeletons can be useful during manual work tasks, such as maintenance work and manual drilling. A common optimistic hope is that this technology opens up more tasks for women. This technology does not come without drawbacks, however. Industries could start using exoskeleton technology to mitigate health problems from work tasks rather than addressing and solving the issues that cause the problems in the first place.

-   **Augmented operator** -- Augmented reality glasses allow for overlaying digital information onto the real world. This technique has many possible uses in the mining industry that would help provide and translate information for the operators while they are out working. It includes having work instructions show the operators what they need to interact with and when, navigational aid within mines and displaying machine information such as fuel levels.

-   **Virtual operator** -- VR technology provides interactive 3D visualizations by, for example, allowing operators to train and interact with a virtual machine before working with a physical one. In the mining industry, through cameras, VR technology could simulate sitting inside the cabin of a machine while the operator would in reality be sitting in a control room, allowing for more accurate remote control. It also allows for training simulations to become more realistic or engaging. The combination of VR technology and remote-controlled machines could, however, lead to outsourcing parts of production control to low-wage countries becoming a more viable and attractive prospect.

-   **Healthy operator** -- Tracking of operators' health values and position allows for notifying them of danger, identifying injured people and locating them. This approach can help locate people and provide vital information if an accident, such as a cave-in, were to occur in the mine. The technology can also be used to better monitor and organize the operators in the mine. For example, operators can be guided based on monitoring data to travel through safer paths with less traffic, which will make navigating the mine safer and more efficient. At the same time, one must be aware that these systems are a threat against personal integrity and must be handled with care. The technology could be used to control workers rather than the process. In a safety-critical situation, this type of human tracking might be welcomed, but the information could also be misused.

-   **Smarter operator** -- Intelligent personal assistants (IPAs) will, through voice interaction technology, allow an operator to more easily interface with machines and digital systems. For example, an operator would be able to vocally ask the IPA where certain vehicles are, and the IPA would map out a route. For a mining operator, an IPA could make it easier to access and manage information while out working or performing maintenance. IPAs could also be used to control semi-autonomous machines vocally, for example, by asking a drill to drive to a specific part of the mine.

-   **Collaborative operator** -- Advancements in industrial robot technology would allow for robots more capable of avoiding collisions with any nearby people or objects. This technology would allow operators to work side-by-side with industrial robots and would help make tunnels, where mining vehicles travel, safer for the employees. The optimistic perspective for this technology sees that the robots take over the dangerous, unergonomic and/or tedious work tasks, letting the employees focus on interesting and safe work tasks. From a pessimistic perspective, robots and technology take over all jobs, essentially replacing the people with machines. The fear of this replacement occurring must be taken into account when implementing the technology to not cause worry or incite resistance from the employees.

-   **Social operator** -- The utilization and implementation of social networking technology in the organization would allow for better communication possibilities between operators and machines. Such possibilities also allow for more opportunities for informal knowledge sharing between operators. With the development and implementation of 5G networks in mining industries, operators and machines can utilize high-speed connections to communicate even from below ground. The greater capabilities to stay connected could, however, lead to a thinning of the lines between work and spare time due to employees' being more readily available at all times.

-   **Analytical operator** -- With more data being gathered from machines and systems, operators can better understand their performance and status. In addition, the increased amount and types of information allow for better forecasts of system and machine performance. This improvement allows for better scheduling of more types of maintenance work. The increased data flow can also come to affect the mining operators because their work tasks could be focussed more on optimization and development.

This classification points to the numerous possibilities of integrating Industry 4.0 with human labour, with some good and some bad. However, this development is not about *creating new* kinds of jobs. Rather, it is a development indicating that most current jobs will be *influenced* by these characteristics and developments. Miners will not disappear, but they will be different in the future.
