# Acceptance of new technology -- the most prominent theories 

```{block, type='chap-auth'}
Lisa Öman Ekervhén and Camilla Grane
```

Introducing new technology in the mining industry is a constant process, one that is important for future development. A challenge in all changes, including the introduction of new technology, is user acceptance. Acceptance of new technology reduces the risk of reluctance and misuse. User acceptance can be created if you understand the psychological processes behind and have a user perspective when purchasing, developing and introducing new technology. The purpose of this chapter is to give a brief overview of theories/models that are important for understanding which factors affect the acceptance of new technologies.

Organizations in the modern industrialized world face a rapidly evolving environment that requires change to be able to keep up with the requirements, and the mining industry is no exception. First, we need to state that the human is generally sceptical about change; there is a fear of the unknown. Change can be perceived as stressful, which leads to negative emotions and feelings of uncertainty that in turn can affect acceptance. There is of course variation in how well individuals embrace and accept change. However, for technologies to be useful, they must be accepted and used by the employees in the organization (Venkatesh, Morris, Davis & Davis, 2003). Therefore, when introducing new technology, there are several aspects that need to be considered to gain acceptance and succeed in implementation. We will now give a brief overview of the most prominent theories in this area.

## The Theory of Planned Behaviour (TPB)

When new technology is introduced, we may think that the employees' attitudes towards the technology play an important role. However, the relationship between attitudes and acceptance is complex. It could be argued that attitudes only matter if they actually influence behaviour (Arnold & Randall, 2016), i.e., if the employees have a negative attitude towards the new technology and hence resist using it. In fact, research has shown that the link between attitudes and behaviour is not that straightforward and that it is quite complex (e.g., Arnold & Randall, 2016). Employees may have a negative attitude but still use and accept the new technology, or they may have a positive attitude but resist using it anyway. Hence, there are further factors that need to be considered when predicting acceptance and future behaviour. 

One such prominent theory that takes other factors into account is the theory of planned behaviour (TPB), developed by Ajzen and Fishbein (1980, read in Ajzen, 1991). The theory is useful when the decision to engage in a particular behaviour is assumed to be the result of a rational process. In other words, humans decide how to behave after considering different behavioural options and evaluating different possible outcomes (Branscombe & Baron, 2017). The decision will lead to an *intention* to perform the chosen behaviour. Intentions are assumed to capture the motivational factors that influence a behaviour and are suggested to be a good predictor of actual behaviour (Ajzen, 1991). In general, the stronger the intention to engage in a specific behaviour, the more likely the behaviour will be performed. According to the theory, intentions are formed and determined by three factors: a*ttitudes towards the behaviour*, s*ubjective norms* and p*erceived behavioural control* (see @fig:figure161).

![Theory of planned behaviour (Ajzen, 1991)[^760]  ](./media/17-acceptance-of-new-technology-–-the-most-prominent-theories/media/image1.png){#fig:figure161}




[^760]:  Icons from Noun project designed by A. Uddin, G. Cresnar, J. Pictos, Popcornarts, and Corpus delicti.

The first factor, *attitude towards the behaviour*, refers to "the degree to which a person has a favourable or unfavourable evaluation or appraisal of the behaviour in question" (Ajzen, 1991, p. 188); in other words, in this context, whether the employees believe that the implementation of new technology will have positive or negative consequences. If the attitude is positive, the intention to use the new technology will be stronger. The second factor, *subjective norm,* refers to "the perceived social pressure to perform or not to perform the behaviour" (Ajzen, 1991, p. 188). In other words, the intention to use the new technology will be affected by the opinions of other people, whether they approve or disapprove the use, and how much the person cares about others' opinion. If a prominent group member shows strong attitudes towards or against the technology, the other group members may follow and make that person\'s opinions their own. The third factor is the degree of *perceived behavioural control*, which refers to "the perceived ease or difficulty of performing the behaviour and is assumed to reflect past experience and anticipated impediments and obstacles" (Ajzen, 1991, p. 188), i.e., people's appraisals of their ability to perform the behaviour. 

Let us suppose that an organization implements new technology and wants to predict whether the employees will use and accept the technology. Acceptance will then, according to the theory, depend on the employees' own attitudes towards the technology, the perception of prominent others' attitude towards the technology and the perception of technology usefulness and behavioural control. The theory of planned behaviour is suggested to be applicable to several workplace issues and situations. Although the theory does not offer a complete explanation for the link between attitudes and behaviour, it highlights some important factors that need to be considered when for example wanting to predict the acceptance of new technology (Arnold & Randall, 2016). 

## The Technology Acceptance Model (TAM) {-}

The theory of planned behaviour (Ajzen & Fishbein, 1980, read in Ajzen, 1991) provides a model of what factors influence our intentions to use a system and actual use of the system, i.e., the person\'s behaviour. Researchers have studied this phenomenon further and, among other things, delved into what creates our attitudes towards behaviour, that is, what makes us positive or negative about using a system from the beginning. Davis (1993) has developed a theory called the technology acceptance model (TAM), in which he focusses on systems and their effects on use behaviour. Since the model has a system focus, it uses the terms *attitude to use* and *actual use* instead of attitude to behaviour and behaviour. Davis (1993) suggests that there are two main factors, related to the system, that influence the attitudes towards using and actual use of a system. These two factors are the user's perceived usefulness of a system (*perceived usefulness*) and the experience of how easy the system is to use (*perceived ease of use*). The technology acceptance model, with its factors and interconnections of the factors, is shown in @fig:figure162. To understand the model, we need to understand the two influencing factors better. 

What is meant by *perceived usefulness* and *perceived ease of use*? *Perceived usefulness* is defined by Davis (1993) as \"the degree to which an individual experiences that using a particular system would enhance his or her job performance (p. 477), in other words, whether the system makes the user more productive. Usefulness addresses both the process and outcome. Therefore, it could also be used on a system that improves safety. A well-functioning fire alarm, for example, would be classified as having good usefulness. Enhancing job performance can be exemplified with a copying machine. If a person needs to copy a document to several different people, the option may be to either hand write multiple copies or use a copier. The copier will most likely be perceived to facilitate the task and improve both the process and the outcome and thus will be perceived as more useful. *Ease of use* is defined by Davis (1993) as \"the degree to which an individual experiences that using a particular system would be free of physical and mental effort\" (p. 477), in other words, whether the system is perceived as easy to understand, learn, and use. In the example of copying, it is easy to understand how to do it when the task is to manually write the same text in several copies. However, handwriting can be experienced as labourious and tiring and thus may reduce the sense of ease. A copier may be more efficient, but most people probably have their own experience that it may be unnecessary difficult to understand how to use some copiers. User interfaces can be both intuitive and easy to use, but they can also be very complicated, complex and difficult to understand. A basic prerequisite for a system to be considered easy to use is that it can be used without a manual, at least the second time the system is used. The mental and physical effort needed to solve the task should be low, and the accuracy of the outcome should be high.

TAM also describes how the system affects the use through perceived usefulness and perceived ease of use; i.e., the model describes how the various factors influence each other. In @fig:figure162, the connections that have been shown to have the greatest significance are marked with bold arrows, while weaker connections have been marked with thinner arrows. To begin with, the model shows that perceived ease of use reinforces perceived usefulness. The reverse, however, does not apply. Increased usefulness does not result in increased perceived ease of use, a point that can be explained by the ease of use simplifying the process and thereby providing increased productivity, which is part of perceived usefulness. A copier can thus gain increased usefulness by simplifying the user interface. The process of making a copy of a document is simplified if it is easy to understand how to perform. The process becomes cumbersome and ineffective if you first need to read a manual or ask a colleague for advice. However, adding more features to the copier, such as adding the ability to also scan documents, or making the copier more efficient, such as making it print twice as fast, does not change how easy it is to use. Ease of use affects usefulness, but usefulness does not affect ease of use. The model (@fig:figure162) also shows which factors affect actual use the most. Davis (1993) found that it is primarily the perceived usefulness that influences whether the system will be used. If the system is perceived to be useful, then that perception is likely to have a positive effect on the attitude towards using it, but it could also have a direct, positive effect on actual use. That is, a system that has high usefulness may be used even if the person has a negative attitude to the system. It may be that they rather would have had a different system, but that the system nevertheless fulfils a function and is therefore used. Ease of use does not have the same direct effect on use. Ease of use enhances the experience of how useful the system is and improves the attitude towards the system. Since a positive attitude towards using the system increases the chance that the system is actually used, ease of use has an indirect, positive effect on its use.

As a summary, when purchasing a new system, it is first and foremost important to ensure that it corresponds to an actual benefit and thus is useful. The system should improve the outcome, e.g., provide increased quality, quantity, accuracy or safety. The system should also streamline the execution of a task, such as reducing time and effort. An easy-to-use system makes the design more efficient; thus, it is also an advantage if the system is perceived as easy to use in addition to being useful.

![The Technology Acceptance Model (Davis, 1993) [^65] ](./media/17-acceptance-of-new-technology-–-the-most-prominent-theories/media/image2.png){#fig:figure162}



[^65]: Icons from Noun project designed by Strokeicon, A. Uddin, G. Cresnar, M. Polakovic, and Corpus delicti.

## Unified Theory of Acceptance and Use of Technology (UTAUT) {-}

There are many models that attempt to determine what factors affect information technology acceptance among users. Based on eight such prominent models, including the previously described TPB and TAM, Venkatesh and colleagues (2003) presented a unified model, called the unified theory of acceptance and use of technology (UTAUT). The model has been found to explain 70% of the variance in user intention (Venkatesh et al., 2003) and 50% of that in technology use (Venkatesh, Thong, & Xu, 2012). According to UTAUT, four constructs are direct determinants of user acceptance and usage behaviour: *performance expectancy, effort expectancy, social influence*, and *facilitating conditions* (see @fig:figure163). The four constructs are briefly described below.

The construct *performance expectancy* is defined, by Venkatesh and colleagues (2003, p. 447), as "the degree to which an individual believes that using the system will help him or her to attain gains in job performance". It is suggested to be the strongest predictor of behavioural intention to use and accept the technology (e.g., Zuiderwijk, Janssen, & Dwivedi, 2015). This point implies that it is of great importance to make the usefulness of the new technology visible to the workers. 

The second construct, *effort expectancy*, is defined as "the degree of ease associated with the use of the system" (Venkatesh et al., 2003, p. 450). In other words, although the users believe the technology to be useful, it will not be accepted unless they also believe the technology to be easy to use. It is therefore important to build and design technology on human terms. It may seem obvious that a technology should be useful and both efficient and effective to use. However, there are often several needs that are missed in the process. Some specific demands for operators in the mining industry that are important to consider when investing in usable technology are presented in Chapter 19, *Adapting the technology to the miners*.

Third, *social influence* is defined as "the degree to which an individual perceives that important others believe he or she should use the new system" (Venkatesh et al., 2003, p. 451). The opinions of colleagues, managers, supervisors, family and friends may therefore be salient when an individual user is forming an intention to use new technology, a point that is especially true in mandatory settings, i.e., when using the technology is not optional (e.g., Venkatesh et al., 2003). The influence of others\' opinions tends to be highest in the early stages of experience with the technique, before the individual has had time to form their own opinion, implying that it is important to view the implementation of new technology as a group process and therefore also handle that implementation on a group level. Further, it is also extremely important to remember that workers are influenced by the management; therefore, managers must communicate support and believe in the system. In other words, acceptance of the technology must permeate the entire organization.

The fourth construct, *facilitating conditions*, is defined as "the degree to which an individual believes that an organizational and technical infrastructure exists to support use of the system" (Venkatesh et al., 2003, p. 453). This construct includes things such as the need for users to feel that they have the resources and knowledge necessary to use the system and that it is supported by the organization. This point implies for example that proper instruction and training is needed before the implementation and that assistance is available if difficulties with using the technique arise. 

The UTAUT also consists of four moderating factors: gender, age, experience and voluntariness of use (see @fig:figure163). These moderators are expected to affect the relationship between the constructs and the intention to accept/use the technology. For example, performance expectancy has been found to be more salient for men and younger workers (compared with women and elderly workers), while the opposite is found for effort expectancy. Further, women are suggested to be more sensitive (than men are) to others' opinions when forming an intention to use new technology; however, the effect declines with experience. The complex interactions for gender and age are something to consider to be able to create equitable workplace environments for women and men of all ages (Venkatesh et al., 2003). For more about that topic, see Chapter 19.

![The variables and moderators in the UTAUT model (Venkatesh et al., 2003)[^504]  ](./media/17-acceptance-of-new-technology-–-the-most-prominent-theories/media/image3.png){#fig:figure163}




[^504]: Icons from Noun project designed by A. Coquet, S. Singh, M. Polakovic, G. Cresnar, A. Uddin, G. Higgins, J. Pictos, and Corpus delicti.

Since this model was introduced, it has been used extensively by researchers when trying to explain the acceptance and use of technology. Although the model has been successful, newer research has found that these constructs and moderators are not always applicable to all contexts, and some crucial constructs may be excluded (Dwivedi, Rana, Jeyaraj, Clement, & Williams, 2019). Many studies have not utilized the moderating factors (Venkatesh et al., 2012); one explanation might be that there may not be any variation in the moderators (Dwivedi et al., 2019). As an example, the organization might have decided that the use of the technology is mandatory, which makes the moderator voluntariness not applicable. Dwivedi and colleagues (2019) further argue that the UTAUT model is missing one important aspect, namely, the individual perspective. Attitudes, an individual's positive or negative feelings about performing the target behaviour, play an important role in accepting technology, as suggested in the TPB model. They found that attitude had a central role in an individual's intention to use the technology and that it also had a direct effect on usage behaviour. Therefore, it is proposed that attitude should be an integral part of the UTAUT model in the future. 

## Beer's theory of organizational change  {-}

Implementing new technology also often means an organizational change. Acceptance of new technology is therefore somewhat linked to the success of the organizational change. Unfortunately, approximately 70% of initiated changes fail (e.g., Burnes, 2011). It is therefore of great value to have an effective approach for organizational change. A rational approach to change is Beer's theory of organizational change (Beer 1988, read in Hughes, Ginnett, & Curphy, 2015). This model includes many of the issues raised by other researchers in the field and highlights what is important for leaders in organizations to consider if they want to be successful with their change effort. The model can be used as a road map when wanting to implement an organizational change and as a diagnostic tool to determine what went wrong if an investment failed to meet its promises (Hughes et al., 2015). Beer has proposed a formula for organizational change, as seen in @fig:figure164.

![Beer's (1988, read in Hughes et al., 2015) formula for organizational change[^47] ](./media/17-acceptance-of-new-technology-–-the-most-prominent-theories/media/image4.png){#fig:figure164}



[^47]: Icons from Noun project designed by A. Coquet, G.K. Lay, and M.R. Alam.

***C*** stands for the **amount of change** that is achieved, and of course "the more the better". However, the amount depends on the levels of the other factors in the formula, which needs to be considered to be successful with the change. These factors are briefly described below and exemplified with introducing new technology in a mining context.

The ***D*** in the formula stands for the employees' **dissatisfaction** with the current situation. How satisfied the employees are with the current situation is an important factor when trying to accomplish change, because satisfied employees are much less willing to change. In other words, if the employees are satisfied, a key factor for change is to increase dissatisfaction, or stated more positively, to ensure that the employees understand and see the value with the planned change. Let us exemplify: if the organization is about to introduce new technology, then it might be a good idea to first determine how satisfied the employees are with the current situation and/or present technology. If they are satisfied, but the organization nonetheless sees the need for new technology, then it is necessary to stress its importance, which can be done by highlighting economic, competitive, legal, technological and social challenges that the organization faces and what can happen if the change, e.g., dismissal of personnel, bankruptcy, or safety risks, is not implemented (Hughes et al., 2015). 

The ***M*** stands for the **model for change**, which primarily constitutes a clear vision for the change and goals that the change is trying to accomplish. The vision should provide guidance for the organization's action, that is, what needs to be changed to fulfil the vision and accomplish the goals (Hughes et al., 2015). To exemplify, the vision could be to be the most attractive mining company in Sweden. To reach that vision, a set of goals needs to be established. One goal can for example be to increase safety. After setting up the goals, which systems need to change to fulfil the vision and accomplish the goals must be decided (Hughes et al., 2015). For example, to reach the goal to increase safety, the organization might decide to implement new technology such as positioning technology. However, to be successful, one needs to think about how changes in one system can affect other parts of the organization (Hughes et al., 2015). For example, if the goal to increase safety includes implementing positioning technology, employees\' reaction to that needs to be considered (see Chapter 17). Hence, to increase the odds for a successful change, it is of great value to anticipate possible problems and consider how changes in one system can lead to consequences for other parts of the organization.

The ***P*** symbolizes the **process**, which consists of the development and execution of the change plan. A change plan should answer the questions of *what, who, when, where* and *how* the change will happen (Hughes et al., 2015). It might also include planned actions for how to handle possible resistance and how to highlight the importance for change if employees are satisfied with the current situation. A thorough communication plan is also needed, as it is important that all parties are well informed throughout the process. A good way to get the employees committed to the change plan is to let those who are affected by the change be part of creating the plan. Of course, that is not always possible; in that case, it is suggested that commitment to the plan can be increased if the personal benefits of the change are made clear, the expectations are explicitly stated, and there is a trusting relationship between the employees and the leaders (Hughes et al., 2015). In the case of implementing positioning technology, the model suggests that it might be a good idea to let the employees be involved in an early stage to ensure commitment (see also Chapter 17). The resistance may be reduced if they receive a chance to express their fears and suggest solutions, for example on how the information should be handled.

***R*** stands for **resistance**. As already mentioned, people often resist change, which can partly depend on fears of the unknown and of loss. The employees might fear that the change will result in loss of identity, of close relationships with others, of power, or of being seen as competent (Hughes et al., 2015). Resistance can also stem from a temporary drop in performance, which is very common when employees learn new systems and skills. These types of sources for resistance should be taken into account in the change plan. In the case of implementing positioning technology that handles personal information, there might be a fear of violation of privacy and misuse of information (see Chapter 17). One way to handle such fear is to listen to possible concerns and let the employees be part of the change plan.

This model suggests that it is possible for the organization to increase the amount of change by considering different aspects. The level of change can be increased by increasing the level of dissatisfaction with the current situation by communicating the importance and value of the change, presenting a clear vision, developing a well thought-out plan for the change, or by decreasing the employees' level of resistance. However, as seen in @fig:figure164, the model is multiplicative, which means that none of the factors can be null if change is about to occur. For example, it does not matter how well thought-out the change plan is or how clear the vision is if there is no dissatisfaction, i.e., the employees are satisfied with the current situation. On the other hand, if there is dissatisfaction with the current situation but there is no plan, then little change will occur. Hence, the model both explains why a change could fail and how to avoid a failure.

## The importance of fairness, justice and trust in the workplace {-}

More general psychological concepts that affect emotional and behavioural reactions to the work environment are the perception of fairness, justice and trust in the workplace. The different concepts will be briefly explained below and related to the context of implementing new technology.

### Perception of justice and fairness {-}

Humans are highly motivated to strive for justice and have a strong need to feel that they are being treated fairly. These needs are so strong that they have a significant effect in the workplace. Perceptions of justice have been found to affect, for example, job performance, respect for leaders, trust in the organization, thoughts of quitting and tendency to file lawsuits (Conte & Landy, 2018). There are various types of justice in the workplace; the most frequently discussed are *distributive justice, procedural justice*, and *interactional justice* (see @fig:figure165).

Distributive justice, which refers to whether the employees believe they have received (or will receive) fair rewards, are perhaps not that applicable in the context of implementing new technology. However, one example could be if different units receive access to different types of systems; for example, some receive mobile phones while others receive COM radios as communication tools. It should be remembered that distributed justice contributes to the overall perception of the workplace, and employees are found to work harder towards organizational goals if they feel that they are working in a fair and just workplace (Conte & Landy, 2018). Therefore, acceptance towards using new technology may also be indirectly affected by a general feeling of justice. 

Procedural justice refers to the perception of the fairness of the policies and procedures used in making decisions in the workplace (Greenberg, 1990, read in Alge, 2001). For processes to be perceived as fair, it is important for the employees to feel that they have the opportunity to influence processes and/or outcomes by, for example, being able to express an objection if they believe that the organization has taken an unfavourable action (Conte & Landy, 2018). It is also important that the employees believe that the organization truly cares and listens to their objections; otherwise, the processes will not produce feelings of justice and fairness. When implementing new technology, it is therefore important to ensure that there is an opportunity for employees to give input into the process and express their hopes and fears. It is equally important for the leaders of a change to show that they genuinely consider the employees\' opinions.

Interactional justice refers to how well the employees are treated when procedures are implemented and is suggested to consist of two specific types of interpersonal treatment, namely, *interpersonal justice* and *informational justice* (Colquitt, Conlon, Wesson, Porter & Ng, 2001). Interpersonal justice reflects the degree to which the employees are treated with politeness, dignity, and respect by the organization. Informational justice focusses instead on the explanations provided to the employees about why procedures were used in that way and hence stresses the need for high-quality communication (Colquitt et al., 2001). When implementing new technology, it is therefore very important to have well-functioning and thorough communication and to give explanations for the change. Equally important is the communication style, which should be warm and supportive.

The feeling of being treated fairly influences a wide range of emotional and behavioural reactions, as mentioned in the beginning of this section. The perception of justice has been found to make the employees accept less-than-perfect working conditions (Conte & Landy, 2018). On the other hand, the perception of injustice has been proposed to have an even greater impact than justice and can for example lead to retaliation and reduced effort. Once this feeling has arisen, it is extremely difficult to undo the harm. It is therefore important to give thorough information about the process, ensure that the employees can voice their opinions and treat the employees with respect and empathy.

![Types of justice (Conte & Landy, 2018)[^928] ](./media/17-acceptance-of-new-technology-–-the-most-prominent-theories/media/image5.png){#fig:figure165}




[^928]: Icons from Noun project designed by A. Coquet, D. Kunze, J. Pictos, and S. Wauters.

### Trust {-}

Many barriers to acceptance of change can be structured under *trust*. Trust is a psychological state, i.e., more an expectation than a reality (Conte & Landy, 2018). In a broad context, trust means a belief about how a person or an organization will act on some future occasion which is based upon previous interactions with that person or organization (Conte & Landy, 2018). There are different types of trust. Three types that are relevant in this context are *interpersonal trust*, *organizational trust* and *technological trust* (Montague & Chiou, 2014, see @fig:figure166)*.* Interpersonal trust concerns trust between persons, for example, an employer's belief that he or she can trust another person at work, e.g., a colleague (Anderson & Dedrick, 1990). Organizational trust is the belief that the supervisors and the organization can be trusted (Mayer, Davis, & Schoorman, 1995). These two types of trust have been found to be especially important when implementing technical systems that collect personal information. To accept such technology, the employees must trust that the people who have access to the information (which can be both colleagues and management) will handle it with care and not misuse the information (see also Chapter 17 for a discussion on this topic). Further, trust in management is a good predictor of lower levels of resistance to change. If the organization lacks, or has lost, the employees' trust, then resistance will be higher, and change will be more difficult to achieve. Technological trust refers to workers\' trust in a technology (Timmons, Harrison-Paul, & Crosbie, 2008). Concerning trust in technology, it is especially important that there is an appropriate level of trust (Montague & Chiou, 2014). Over-trust or overreliance in the technology and distrust and under-trust can be damaging to work outcomes (@fig:figure166). Over-trust in technology can make the workers careless and complacent. For example, the use of positioning technology can make the control room workers rely too heavily on the technology and hence not have a backup plan for a manual rescue operation in case of power failure. On the other hand, distrust among workers, or workers' distrust of technology, may lead to inappropriate or non-use of the technology (Montague & Chiou, 2014). If workers are required to use technologies that they do not trust, they might create ways to avoid using the technology, which can lead to errors. One such example can be that the workers do not trust the use of the positioning technology and therefore resist wearing the tag and hence remove it, which may lead to devastating consequences in case of a fire or when blasting.

If the newly introduced technology reduces efficiency, decreases safety and is difficult to use, it can negatively impact employee trust in the organization (Montague & Chiou, 2014). Further, it is found that people who have lost trust begin to seek out information that will confirm their distrust, and they are less open to information that challenges that distrust (Conte & Landy, 2018). In other words, previously handled implementations can affect how new technology is accepted. Trust is difficult to build but easy to lose (Kramer, 1999). Further, once trust in an organization has been lost, it is extremely hard to rebuild (Conte & Landy, 2018). Have in mind though, that explanations and apologies can help repair the damage done by violations of trust (Conte & Landy, 2018), which goes hand in hand with the recommendations to ensure that the workplace is perceived as just and fair. 

![Different types of trust[^937] ](./media/17-acceptance-of-new-technology-–-the-most-prominent-theories/media/image6.png){#fig:figure166}



[^937]: Icons from Noun project designed by A. Coquet, G.K. Lay, Graphic Enginer, and LAFS.
