# Acceptance of new technology

Introducing new technology in the mining industry is the future but will
the users accept the new technology? The purpose of this chapter is to
give a brief overview of theories/models that are important for
understanding which factors affect the acceptance of new technologies.

Organizations in the modern industrialized world face a rapidly evolving
environment that requires changes to be able to keep up with the
requirements, and the mining industry is no exception. First we need to
clarify that the human is generally skeptical about change, there is a
fear of the unknown. Change can be perceived as stressful which leads to
negative emotions and feelings of uncertainty which in turn can affect
acceptance. There is of course variation in how well individuals embrace
and accept change. Regardless, when introducing new technology there are
several aspects that needs to be considered to gain acceptance and
succeed with the implementation. We will now give a brief overview of
the most prominent theories in this area.

## Theory of planned behavior (TPB)

...

## The Technology Acceptance Model (TAM)

Inte genomarbetad text ännu.

Technology is accepted when it is perceived as useful and easy to use.
System design also affects user acceptance. In a study by Davis (1993),
perceived usefulness was found 50 % more important for user acceptance
than ease of use. That means, it is important to design based on user
needs. Davis (exemplifies what is meant by perceived usefulness: the
system is perceived to improve quality of work, gives greater control,
enables the worker to accomplish tasks faster, supports critical aspects
of work (i.e. decision making or monitoring), increases productivity,
improves job performance, enhances effectiveness, and makes it easier to
do the job. If a technology solution does not clearly show high
usefulness by the user the user may be reluctant to use it. A system
that is designed to control workers has high usefulness for management
personnel but not necessarily for the workers. Highly effective workers
may be positive to a control system since they may profit from their
effectiveness being measured and observed. A control system may also be
perceived as useful if its purpose is related to increased personal
safety. Acceptance will be low if the workers do not see any own
benefits coming from the system.

## Unified Theory of Acceptance and Use of Technology (UTAUT)

There are many models that attempts to determine what factors that
affect information technology acceptance among the users. Based on eight
such prominent models, including TPB and TAM, Venkatesh, Morris, Davis
and Davis (2003) presents a unified model, called the Unified Theory of
Acceptance and Use of Technology (UTAUT). According to UTAUT, four
constructs are direct determinants of user acceptance and usage
behavior, namely; *performance expectancy, effort expectancy, social
influence*, and *facilitating conditions*. Below the four constructs are
briefly described.

The construct performance expectancy is defined, by Venkatesh and
colleagues, as the degree to which an individual believes that using the
system will help him or her to attain gains in job performance. It
implies that it is of great importance to make the usefulness of the
technology visible for the workers. Something more here?

The second construct, effort expectancy, is defined as the degree of
ease associated with the use of the system. It is important to build and
design technology on human terms. It may seem obvious that a technology
should be useful and be both efficient and effective to use. However,
there are often several needs that are missed in the process. Some
specific demands for operators in the mining industry that are important
to consider when investing in usable technology is presented in Chapter
x (Technology on human terms in a mining context).

Third, social influence is defined as the degree to which an individual
perceives that important others believe he or she should use the system.
In the mining context, it means that the attitude to new technology can
be influenced by the attitudes of the colleagues. It's a group
process....

The fourth construct, facilitating conditions, are defined as the degree
to which an individual believes that an organizational and technical
infrastructure exists to support the use of the system. Leaders must be
positive... Proper training and information...

The UTAUT also consist of four moderating factors which is gender, age,
experience and voluntariness of use. However, these moderators are not
always applicable to all context because there might not be any
variation (Dwivedi, Rana, Jeyaraj, Clement & Williams, 2019). As an
example, the organization might have decided that the use of the
technology is mandatory, which makes the moderator voluntariness not
applicable.

Instead, Dwivedi and colleagues (2019) argues that the UTAUT model is
missing out one important aspect, namely the individual perspective.
They suggest that attitudes, an individual's positive or negative
feelings about performing the target behavior, play an important role in
accepting technology.

## Beers theory of organizational change

\...

### Individual factors

### Trust

Many barriers for acceptance of change can be structured under *trust*.
Trust in management is a good predictor of lower level of resistance to
change. If however the organization doesn't have, or has lost, the
employees trust, then resistance will be higher and change will be more
difficult to achieve.

This section will be expanded. (read Conte & Landy, 2018; Korunka &
Hoonakker, 2014)

### Perception of fairness

It has been well-established that fairness plays a key role in
determining reactions to organizational events such as EPM (electronic
performance monitoring). Procedural and interactional justice, will
relate to perceptions of fairness.

### Technology maturity
