# Positioning technology -- safety vs privacy concerns, or: use vs misuse

This chapter discusses the positive effects of a positioning technology
from a safety perspective and sets it against privacy concerns. Factors
that need to be considered to enhance privacy and reduce the perception
of misuse are discussed.

As can be read in Chapter 2, a recommendation for creating attractive
workplaces in the mining industry is to have health and safety at work
as a top priority. This can be achieved through mechanization, remote
control and automation, as well as a developed safety climate. An
additional way to increase safety is to use new and advanced
communication and positioning technology that works in a mining
environment. The communication and positioning technology allows
real-time location, tracking and monitoring of vehicles, personnel and
equipment. The information can be available both in control rooms on the
surface and underground on mobile phones and tablets. Such technology
entails everybody, wherever they are located, information about what is
going on down below (and above ground).

From a safety perspective, it is of course a great advantage to see
peoples' exact location, for example, in case of a fire or a cave-in
that requires evacuation of the mine. In such situations, time is of
great importance. Without positioning technology, the rescue personnel
needs to spend a lot of time on getting confirmation about each worker
that they are in a safe location. With a positioning system, this phase
goes much faster and instead focus can be on those who have not reached
safety and take decision about who need attention first.

Today\'s technology makes it possible to also collect other types of
information from both the environment and from humans. Via sensors,
information regarding machine functionality, temperature, tensions,
vibrations and similar can be collected. A rather new concept is sensors
worn by humans, measuring human conditions. Physiological sensors can
provide information about *personal health* such as pulse and
temperature; biokinetic sensors can measure posture and body movements
(*position*); and ambient sensors can measure environmental factors such
as temperature och sound pressure level (Johny & Anpalagan, 2014; Figure
1). These systems could also be useful as a preventive safety system or
in case of an accident as the information can be shared with other
workers close by, control room personnel, and rescue personnel.

Doubtlessly, this is a great advantage - but what does the workers
thinks about such technology? In a safety critical situation this type
of human tracking might be accepted by the workers, but the information
could also be misused. As can be read in Chapter 6, one must be aware
that this kind of systems are a threat against personal integrity and
must therefore be handled with care. According to @zweig2002 there is a
growing acknowledgment that technologies that track presence and
activity lead to privacy concerns. Hence, when implementing such
technology, psychological aspects must be taken under consideration.

![Information that are possible to collect by positioning
technology and wearable sensors. The picture of the process operator is
borrowed from Boliden.](./media/image1.png){width="5.510416666666667in"
height="3.1666666666666665in"}



## Important psychological aspects to consider

Privacy is defined as the extent to which individuals believe they have
control over their personal information and interactions with others
(Stone & Stone, 1990). If the individual perceives a loss of such
control it can lead to a perception of invasion of privacy. Privacy
concerns are one of the most consistent reactions to awareness systems
(e.g., Lee et al.1997 OBS! read in Zweig & Webster). Hence, positioning
technology and human sensors can lead to the feeling of lost control if
not restricted and handled properly. Based on research and findings in
the SIMS-project and other related projects, we will now briefly
exemplify some psychological aspects that are important to consider in
order to avoid violating privacy and to create acceptance for technique
that collects personal data.

First, the collected information must be perceived as being *relevant,*
i.e. necessary and appropriate to collect. Collected information that is
perceived as relevant are more likely to be viewed as less invasive of
privacy than information that is perceived as irrelevant. It is
therefore extremely important that each bit of information that is
collected can be justified on good grounds. Have in mind, even though
today\'s technology makes it possible to collect all sorts of
information, information should not only be collected because it is
possible. The more the merrier does not apply in this context. For
example, if ones position is of importance only from a safety
perspective, then it may be of less importance to view the name of the
person.

Second, it is of great importance to make the *usefulness* of the
technology visible for the workers to achieve acceptance (performance
expectancy). The organization must be able to communicate *why* such
systems should be implemented. Like when children asks "why", "because"
is not a good answer. Do you like it yourself? Hence, the organization
must be able to justify the use, have a legitimate reason for
implementing the system. From a privacy perspective, the individual
wants to have control over what information the organization has
*access* to, and how the organization will *use* the collected
information (Brandimartie et al., 2012). Most important for accepting to
reveal personal information is likely to be in control over how the
information will be used. In this context, be careful to ensure and
clarify the purposes for collecting possibly sensitive information and
to communicate the true purpose. It is also important to explain the
usefulness clearly. For example, make sure that the workers understand
how the technology will enhance their safety and facilitate rescue
operations. A further aspect is to emphasize the accompanying advantages
such technology can have for the workers in their everyday job, in terms
of being able to locate persons, vehicles and equipment, as well as
providing information about the surrounding environment.

Third, *participation* is a key component for enhancing employees
perception of procedural justice and reduce feelings of invasion of
privacy (Alge, 2001). It is therefore important to allow employees to be
involved in both the design and implementation of the technology. The
workers should be involved at an early stage, even if introducing the
technology is not optional. They should be included when discussing and
deciding what information should be collected, who will have access to
the information, how the information should be stored etc. One advantage
with including workers early in the process is the possibility to
understand the hopes and fears. It is important to be responsive to any
concerns that employees might have and try to sort them out at an early
stage. Therefore, the most sceptical employees can be a valuable
resource. If their concerns are listened to and met, there is a greater
possibility that the technology will be accepted when implemented.

Fourth, our attitudes are influenced by important others, and attitudes
toward positioning technology is no exception. That means that an
individual workers attitude to such technology can be influenced by the
attitudes of the colleagues (*social influence*). This is especially
true in mandatory settings, i.e. when using the technology is not
optional (reference). The influence of others\' opinions tend to be
highest in the early stages of experience with the technique, before the
individual has had time to form their own opinion. This implies that it
is important to see it as a group process and work with the whole
team...

Further, the human strives for the perception of *justice.* To achieve
acceptance it may be of importance that everybody can see everybody\'s
position. If a worker is monitored differently than other coworkers or
persons from another professional role, that worker may experience
injustice (Alge, 2001). The feeling of big brother's watching you should
be avoided. It has also been found that mere suspicion that the
information could be used for performance monitoring creates perception
of unfairness [@zweig2002]. If there is no such
intention with the system, It is important to make that clear.

Another important factor that can affect acceptance for technical
systems that collect personal information is *trust*. Such systems
requires a level of trust in the relationships between colleagues,
managers and the organization.

Another side of trust is overtrust in technology. What happens if the
system goes down because of a power failure? Then it is important to
have back up, manual routines... scenarios... Ska utvecklas (se
Danielsson).

Facilitating conditions, such as the degree to which an individual
believes that an organizational and technical infrastructure exists to
support the use of the system, are also of importance. Leaders must be
positive... Proper training and information...

Information is important... For example, knowledge of who is monitoring
you will result in lower perceptions of privacy invasion. This is
because the targets of information disclosure represent an important
determinant of privacy (Stone & Stone, 1990). Lookback option that
allows employees to see who has been accessing their images.

To summarize:

-   The design and implementation should be done in close cooperation
    with the workers.

-   Thorough information

-   It is important to consider changes as a group process (social
    influence)

-   Make sure that the usefulness is visible for the users

-   Have a close cooperation with the trade unions

-   Proper training

-   Develop a policy; including individual rights, security, how the
    information will be stored, who will have access to what
    information\...

## See also {-}

\ @dwivedi2019

\ @venkatesh2003
