# Technology on human terms in a mining context

This chapter will exemplify aspects important to consider when investing
in new technology that will involve a user. The user is one of the key
components for success, hence much is gained when technology is built on
human terms. In short this means that the technology should meet and
support cognitive demands, personal demands, communicational demands and
environmental demands.

Industries are constantly evolving in terms of modernization of
technology for production and communication at work. The reason for
technology investments are often to increase productivity or safety. If
the technology will involve a user it should be usable. According to the
definition of usability this means that the technology should be
possible to use by specified users to achieve specified goals with
effectiveness, efficiency, and satisfaction in a specified context of
use (ISO 9241-11). So, what does this mean more exactly? The technology
should support effectiveness. This means that the users should not
misunderstand the technology and end up doing unnecessary errors. The
technology should support accuracy and completeness. The technology
should also support efficiency, hence it should use as little resources
as possible. This means that the user should be able to use the system
quickly without spending time on unnecessary steps. It also means that
the users should understand the technology, and not end up wondering
what to do. As far as possible, technology should be self explanatory.
Satisfaction is related to the subjective feeling the user get in
relation to the product. The product should not give the users feeling
of discomfort. The attitude towards the technology should be good. In
this chapter we will mainly focus on aspects that are related to
efficiency and effectiveness. User satisfaction in terms of attitude
towards technology are more closely addressed in the chapter named
Acceptance of technology.

If efficiency, effectiveness and user satisfaction are neglected, the
risk is to end up with large investments that are never used, misused or
too difficult to use efficiently. The investment may end up in large
costs and reduced productivity; the opposite to what was intended.

As long as/whenever a user is included, it is important to build and
design technology on human terms. But what is meant by that? It may seem
obvious that a technology should be useful and be both efficient and
effective to use. However, there are often several needs that are missed
in the process. As an organization, you may not design the technology,
but you can place demands on the designers and help them understand the
specific needs of your personnel. In this chapter we will exemplify some
specific demands for operators in the mining industry that are important
to consider when investing in usable technology. The examples are built
on theory combined with our findings in the SIMS-project and other
related projects.

## Cognitive demands

Learning and support

Over stimulation and under stimulation (Yerkes Dodsons Law for complex
and simple tasks)

Attention, cognitive load

Stress (special needs during accidents)

Reduced cognitive abilities. Important to use high saliency.

## Personal demands

### Age

Age is a large challenge at many workplaces. First we have technology
maturity. New generations may be frustrated when technology at work are
slow or seem fossil. On the other hand, the workforce that have large
experience may lose in speed and efficiency if changes are made
frequently.

### Gender

The main issues that are related to gender are physical demands. When it
comes to investments of new technology it is important to control that
small aspects like the size of the handheld device are big or small
enough to be easily used by both a large and a small hand. Sometimes it
is these small things that make the large investment useless in the end.
And if not useless, the product may cause a lot of frustration and
demand unnecessary effort if a button or likewise can not be reached
easily.

### Disabilities

Dyslexia

Color blindness

## Communicational demands

Humans are multimodal. This means, we are able to take in information
from several senses. This ability is a powerful gift that is difficult
to match with AI. Humans are still a great resource when it comes to
noticing differences in an environment, it could be a smell, a noise,
vibration or a different color. For example, a human can in a few
seconds notice a crack or a leakage on a large area. AI would need
cameras, sensors, programming and extensive training for the same task.
However, when this type of information are to be shared or saved the
communication are often limited to only text or voice messages.

Examples of enriched communication and the gains.

Examples of problems related to communication (filtering)

## Environmental demands

Sound

Vibrations

Dust, steam

Extreme heat or minus degrees. (Mobile phones outdoors during winter in
the north)

Clothes

Reduced visibility (smoke during fire)
