# References {-}

Abrahamsson, L. (2007). Gruvarbetets historia ur ett genusperspektiv.
Hur gruvarbetet blev och förblev manligt [The history of mining from a
gender perspective. How mining became and remained male]. In: Doktare,
H. (Ed.). *OPLOGAT -- spår av kvinnors liv och arbete i Norrbotten*
[UNPLOWED- traces of women\'s lives and work in Norrbotten]. Luleå:
Oplogat produktion.

Abrahamsson, L. (2008). *Organizational gender aspects: a baseline study
of socio-economic effects of Northland Resources ore establishment in
northern Sweden and Finland*. Luleå tekniska universitet.

Abrahamsson, L., & Johansson, J. (2006). From grounded skills to sky
qualifications: a study of workers creating and recreating
qualifications, identity and gender at an underground iron ore mine in
Sweden. *Journal of Industrial Relations*, 48(5), 657-676.

Abrahamsson, L., Johansson, B., & Johansson, J. (2009). Future of metal
mining: Sixteen predictions. *International Journal of Mining and
Mineral Engineering*, *1*(3), 304.
<https://doi.org/10.1504/IJMME.2009.027259>

Abrahamsson, L., Segerstedt, E., Nygren, M., Johansson, J., Johansson,
B., Edman, I., & Åkerlund, A. (2014). *Mining and Sustainable
Development: Gender, Diversity and Work Conditions in Mining*. Luleå:
Luleå University of Technology.

Alge, B. J. (2001). Effects of computer surveillance on perceptions of
privacy and procedural justice. *Journal of Applied Psychology*,
*86*(4), 797.

Andersson, E. (2012) *Malmens manliga mysterium -- en interaktiv studie
om kön och tradition i modernt gruvarbete*. [The male mystery of iron
ore -- an interactive study on gender and tradition in contemporary
mining]. Doctoral thesis. Luleå: Luleå University of Technology.

Åteg, M., Hedlun,d A. and Pontén B. (2004) *Attraktivt arbete. Från
anställdas uttalanden till* skapandet *av en modell.* Arbetsliv i
omvandling, 2004:1, Stockholm: Arbetslivsinstitutet.

Åteg, M., Hedlund, A., Pontén, B., & Arbetslivsinstitutet. (2004).
*Attraktivt arbete: Från anställdas uttalanden till skapandet av en
modell*. Arbetslivsinstitutet.

Brandimarte, L., Acquisti, A., & Loewenstein, G. (2013). Misplaced
confidences: Privacy and the control paradox. *Social Psychological and
Personality Science*, *4*(3), 340-347.

Burnes, B. (2011). Introduction: Why Does Change Fail, and What Can We
Do About It?. *Journal of Change Management, 11*(4), 445-450, DOI:
10.1080/14697017.2011.630507

Crawley, A., & Sinclair, A. (2003). Indigenous human resource practices
in Australian mining companies: Towards an ethical model. *Journal of
Business Ethics*, *45*(4), 361-373.

Davis, F. D. (1993). User acceptance of information technology: System
characteristics, user perceptions and behavioral impacts. *International
Journal of Man-Machine Studies*, *38*(3), 475--487.
<https://doi-org.proxy.lib.ltu.se/10.1006/imms.1993.1022>

Dwivedi, Y. K., Rana, N. R., Jeyaraj, A., Clement, M., & Williams, M. D.
(2019). Re-examining the Unified Theory of Acceptance and Use of
Technology (UTAT): Towards a revised theoretical model*. Inf Syst Front
(21*), 719-734. Doi: 10.1007/s10796-017-9774-y

Elgstrand, K., & Vingård, E. (2013). *Occupational safety and health in
mining: Anthology on the situation in 16 mining countries*. Occupational
and Environmental Medicine, University of Gothenburg.

European Commission. (2003). Directive 2003/10/EC of the European
Parliament and of the Council of 6 February 2003 on the minimum health
and safety requirements regarding the exposure of workers to the risks
arising from physical agents (noise).
https://ec.europa.eu/health/ph\_risk/committees/04\_scenihr/docs/scenihr\_o\_018.pdf

Eveline, J., & Booth, M. (2002). Gender and sexuality in discourses of
managerial control: The case of women miners. *Gender, Work &
Organization*, 9(5), 556-578.

Hägg, G. M., Ericson, M., & Odenrick, S. (2015). Physical load. In Work
and technology on human terms (2nd ed.). Prevent.

Harms-Ringdahl L (2013) Guide to safety analysis for accident
prevention, IRS Riskhantering AB, Stockholm

Harms-Ringdahl, L., & IRS Riskhantering. (2013). *Guide to safety
analysis for accident prevention*. IRS Riskhantering : GML.

Hedlund, A. (2007) Attraktivitetens dynamik -- studier av förändringar i
arbetets attraktivitet, doktorsavhandling i arbetsvetenskap, Högskolan i
Dalarna/Kungliga, Tekniska Högskolan, Stockholm.

Horberry, T., Burgess-Limerick, R., & Steiner, L. J. (2011). Human
factors for the design, operation, and maintenance of mining equipment.
Boca Raton: CRC Press.

Horberry, T., Burgess-Limerick, R., & Steiner, L. J. (2018).
*Human-centered design for mining equipment and new technology*. Taylor
& Francis, a CRC title, part of the Taylor & Francis imprint, a member
of the Taylor & Francis Group, the academic division of T&F Informa,
plc.

Hughes, G., Ginnett, R., & Curphy, G. (2015). *Leadership: Enhancing the
Lessons of Experience*. New York: McGraw-Hill Education.

Johansson J., Johansson B., Lööw J., Nygren M. Abrahamsson L. (2018).
"Attracting young people to the mining industry -- Six recommendations".
International journal of mining and mineral engineering Vol. 9, No. 2,
2018. pg 94-108

Johansson, B., & Johansson, J. (2014). 'The new attractive mine': 36
research areas for attractive workplaces in future deep metal mining.
*International Journal of Mining and Mineral Engineering*, *5*(4), 350.
<https://doi.org/10.1504/IJMME.2014.066582>

Johansson, B., Johansson, J., & Abrahamsson, L. (2010). Attractive
workplaces in the mine of the future: 26 statements. *International
Journal of Mining and Mineral Engineering*, *2*(3), 239.
<https://doi.org/10.1504/IJMME.2010.037626>

Johansson, J., & Abrahamsson, L. (2009). The good work -- A Swedish
trade union vision in the shadow of lean production. *Applied
Ergonomics*, *40*(4), 775--780.
https://doi.org/10.1016/j.apergo.2008.08.001

Johansson, J., Abrahamsson, L., Kåreborn, B. B., Fältholm, Y., Grane,
C., & Wykowska, A. (2017). Work and Organization in a Digital Industrial
Context. *Management Revu*, *28*(3), 281--297.
https://doi.org/10.5771/0935-9915-2017-3-281

Johansson, T., Segerstedt, E., Olofsson, T., & Jakobsson, M. (2016).
Revealing social values by 3D city visualization in city
transformations. *Sustainability*, *8*(2), 195.

Johny, B., & Anpalagan, A. (2014). Body area sensor networks:
Requirements, operations, and challenges. *IEEE Potentials*, *33*(2),
21-25.

Kagerman, H., W. Wahlster and J. Helbig. 2013. Recommendations for
Implementing the Strategic Initiative Industry 4.0. München: Acatech.

Lööw J., Johansson B., Andersson E. and Johansson J. (2019), *Designing
Ergonomic, Safe, and Attractive Mining Workplaces*. New York: CRC Press,
Taylor & Francis.

Lööw, J., & Nygren, M. (2019). Initiatives for increased safety in the
Swedish mining industry: Studying 30 years of improved accident rates.
*Safety Science*, *117*, 437--446.
https://doi.org/10.1016/j.ssci.2019.04.043

Lööw, J., Abrahamsson, L. & Johansson (2019). Mining 4.0---the Impact of
New Technology from a Work Place Perspective, *J. Mining, Metallurgy &
Exploration*. <https://doi.org/10.1007/s42461-019-00104-9>

Lööw, J., Johansson, B., Andersson, E., & Johansson, J. (2019).
*Designing ergonomic, safe, and attractive mining workplaces*. Taylor &
Francis, a CRC title, part of the Taylor & Francis imprint, a member of
the Taylor & Francis Group, the academic division of T&F Informa, plc.

Mayhew, C., Quinlan, M., & Ferris, R. (1997). The effects of
subcontracting/outsourcing on occupational health and safety: Survey
evidence from four Australian industries. Safety Science, 25(1-3),
163--178.

Morberg, M., Bergendahl, H., & Prevent. (2009). *Bättre arbetsmiljö.*
Prevent.

Muzaffar, S., Cummings, K., Hobbs, G., Allison, P., & Kreiss, K. (2013).
Factors associated with fatal mining injuries among contractors and
operators. Journal of Occupational and Environmental Medicine, 55(11),
1337--1344.

Nygren, M., Jakobsson, M., Andersson, E., & Johansson, B. (2017). Safey
and multi-employer worksites in high-risk industries. Relations
industrielles/Industrial relations, 72(2), 223--245.

Osvalder, A.-L., Rose, L., Karlsson, S., Eklund, J., & Odenrick, P.
(2015). Design processes. I Work and technology on human terms (2:a
uppl.). Stockholm: Prevent.

Ranhagen, U. (1989). Renewal of industrial environments: Pt. 1, the
planning process, Pt. 2, principles and case studies. Stockholm: Swedish
Council for Building Research.

Research project at Luleå University of Technology during 2014-2016
*Nordic Mining and the Search for Women. Designing new gender equality
interventions,* project coordinator Eira Andersson.

Ringblom, L. (2019). *Utmanad ordning? En studie av kön och
jämställdhetsarbete i den svenska gruvindustrins arbetsorganisationer*.
[Challenging the gendered order? A study of gender and gender equality
work in the Swedish mining industry]. Doctoral thesis. Luleå: Luleå
University of Technology.

Romero, D., J. Stahre, T. Wuest, O. Noran, P. Bernus, Å. Fast-Berglund,
and D. Gorecky. 2016. Towards an operator 4.0 typology: a human-centric
perspective on the fourth industrial revolution technologies. In
Proceedings International Conference on Computers & Industrial
Engineering (CIE46).

Sarker, S., Valacich, J. S., & Sarker, S. (2005). Technology adoption by
groups: A valence perspective. *Journal of the Association for
Information Systems*, *6*(2), 37-70.

Segerstedt, E., & Abrahamsson, L. (2019). Diversity of livelihoods and
social sustainability in established mining communities. *The Extractive
Industries and Society*.

Simpson, G., Horberry, T., & Joy, J. (2009). Understanding human error
in mine safety. Farnham, England ; Burlington, VT: Ashgate.

SIP STRIM (2019). Strategic Research and Innovation Roadmap for the
Swedish Minong, Mineral and Metal Producing Industry, Stockholm:
Vinnova.

Stone, E.F., & Stone, L.D. (1990). Privacy in Organizations: Theoretical
issues, Research findings, and Protection mechanisms.In G. Ferris & K.
Rowland (Eds.), Research in personnel and human resources management,
Vol. 8, (pp. 549-411). Greenwich, CT: JAI Press.

SveMin. (2010). Occupational Injuries and Sick Leave in the Swedish
Mining and Mineral Industry 2009. SveMin, Stockholm.

Sverige, & Arbetsmiljöverket. (2011). Belastningsergonomi. Hämtad från
http://www.av.se/dokument/afs/afs2012\_02.pdf

Venkatesh, V., Morris M. G., Davis, G. B., & Davis, F. D. (2003). User
acceptance of information technology: toward a unified view. *MIS
Quarterly, 27*(3), 425-478. DOI:10.2307/30036540

Venkatesh, V., Thong, J., & Xu, X. (2012). Consumer acceptance and use
of information technology: Extending the unified theory of acceptance
and use of technology. *MIS Quarterly, 36*(1), 157-178.
DOI:10.2307/41410412

Zuiderwijk, A., Janssen, M., & Dwivedi, Y. K. (2015). Acceptance and use
predictors of open data technologies: Drawing upon the unified theory of
acceptance and use of technology. *Government information quarterly*,
*32*(4), 429-440. http://dx.doi.org/10.1016/j.giq.2015.09.005

Zweig, D., & Webster, J. (2002). Where is the line between benign and
invasive? An examination of psychological barriers to the acceptance of
awareness monitoring systems. *Journal of organizational behavior, 23*,
605-633. Doi:10.1002/job.157
